STORMPATH_CLIENT_APIKEY_ID: 1TRGE6GW7MDQRWWS42CEL6XOR
STORMPATH_CLIENT_APIKEY_SECRET: hz6lN+TQGBMTIbE7v3Ui0h26bKu7TFWvVCYdGCujJko
STORMPATH_APPLICATION_HREF: https://api.stormpath.com/v1/applications/atzOEyqEFkFOS8IB1Fr7m
