STORMPATH_CLIENT_APIKEY_ID: BRL09U3G5JPYCVYEWJSYAFL7X
STORMPATH_CLIENT_APIKEY_SECRET: p2GEvfsF03Q+a0d291yiqOzPEgjog40jKZpTn4w+NJQ
STORMPATH_APPLICATION_HREF: https://api.stormpath.com/v1/applications/6dnQnhQvKsRJClPdjdaHgE
